
server.port=8080
server.servlet.context-path=/lodge

app.name=Lodge
booking.max.nights=30
booking.cancel.min.days=3


mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=CHANGE_ME
mail.password=CHANGE_ME
app.mail=info.lodge@gmail.com
app.url=http://localhost:8080/lodge
app.public.url=http://localhost:8080/lodge

payhere.merchant.id=
payhere.merchant.secret=
payhere.sandbox=true


currency.usd.rate=330

server.servlet.session.timeout=24h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
